export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';
export const POST_CREATE_RESET = 'POST_CREATE_RESET';

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST';
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS';
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL';

export const MY_POST_LIST_REQUEST = 'MY_POST_LIST_REQUEST';
export const MY_POST_LIST_SUCCESS = 'MY_POST_LIST_SUCCESS';
export const MY_POST_LIST_FAIL = 'MY_POST_LIST_FAIL';

export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';
export const POST_LIST_FAIL = 'POST_LIST_FAIL';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';

export const POST_UPVOTE_REQUEST = 'POST_UPVOTE_REQUEST';
export const POST_UPVOTE_SUCCESS = 'POST_UPVOTE_SUCCESS';
export const POST_UPVOTE_FAIL = 'POST_UPVOTE_FAIL';

export const POST_DOWNVOTE_REQUEST = 'POST_DOWNVOTE_REQUEST';
export const POST_DOWNVOTE_SUCCESS = 'POST_DOWNVOTE_SUCCESS';
export const POST_DOWNVOTE_FAIL = 'POST_DOWNVOTE_FAIL';

export const POST_VOTE_REQUEST = 'POST_VOTE_REQUEST';
export const POST_VOTE_SUCCESS = 'POST_VOTE_SUCCESS';
export const POST_VOTE_FAIL = 'POST_VOTE_FAIL';

