export const UPCOMING_GAMES_REQUEST = "UPCOMING_GAMES_REQUEST";
export const UPCOMING_GAMES_SUCCESS = "UPCOMING_GAMES_SUCCESS";
export const UPCOMING_GAMES_FAIL = "UPCOMING_GAMES_FAIL";

export const GAME_PREDICTIONS_REQUEST = "GAME_PREDICTIONS_REQUEST";
export const GAME_PREDICTIONS_SUCCESS = "GAME_PREDICTIONS_SUCCESS";
export const GAME_PREDICTIONS_FAIL = "GAME_PREDICTIONS_FAIL";