export const SUB_CREATE_REQUEST = 'SUB_CREATE_REQUEST';
export const SUB_CREATE_SUCCESS = 'SUB_CREATE_SUCCESS';
export const SUB_CREATE_FAIL = 'SUB_CREATE_FAIL';
export const SUB_CREATE_RESET = 'SUB_CREATE_RESET';
